config/routes.rb
Ma001::Application.routes.draw do

  get   "/(.:format)" => "interrupts_report#index", as: :ir_index
  post  "/get_result(.:format)" => "interrupts_report#get_result", as: :ir_get_result
  get   "/result(.:format)" => "interrupts_report#result", as: :ir_result
  get   "/result/print/:report(.:format)" => "interrupts_report#print", as: :ir_print









   root :to => 'interrupts_report#index'


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/interrupts_report_controller.rb
#encoding:utf-8
require 'zip/zip'
class InterruptsReportController < ApplicationController

  include ReportsFuncs

  layout "ir"

  def index
  end

  #POST /ir/get_result
  def get_result

    data_source = {};

    case params[:data_type]
    when "zip"

      if params[:zip_file]
        zip_file = params[:zip_file].tempfile

        tz = Zip::ZipFile.open(zip_file)

        data_source = load_reports_from_zip tz, LmInterruptsReport.new.data_source_shema
      end

    else
      tp_report_file = params[:tp_report].tempfile unless params[:tp_report].blank?
      fp_report_file = params[:fp_report].tempfile unless params[:fp_report].blank?
      pp_report_file = params[:pp_report].tempfile unless params[:pp_report].blank?
      gl_report_file = params[:gl_report].tempfile unless params[:gl_report].blank?

      data_source[:tp_report] = LmTpReport.new(tp_report_file.read) unless tp_report_file.nil?
      data_source[:fp_report] = LmFpReport.new(fp_report_file.read) unless fp_report_file.nil?
      data_source[:pp_report] = LmPpReport.new(pp_report_file.read) unless pp_report_file.nil?
      data_source[:gl_report] = LmGlReport.new(gl_report_file.read) unless gl_report_file.nil?
    end

    ir = LmInterruptsReport.new source_reports: data_source,
                                      options: {
                                        rayon: params[:rayon],
                                        report_date: Date.today
                                      }

    flash[:interrupts_report] = ir

    #flash[:debug] = data_source[:pp_report]
    redirect_to action: "result"
  end

  #GET /ir/result
  def result
    flash[:interrupts_report] = ir = flash[:interrupts_report]
    #flash[:debug]=ir.details
    render locals: {report: ir}
  end

  #GET /ir/print/:report(.:format)
  def print
    flash[:interrupts_report] = ir = flash[:interrupts_report]
    data=""
    unless ir.nil?
      case params[:report]
      when "recom"
        data = render_to_string "interrupts_report/report_templs/xls/recom",layout:nil, locals: {report: ir}
      when "ovd"
        data = render_to_string "interrupts_report/report_templs/xls/ovd",layout:nil, locals: {report: ir}
      else
        redirect_to root_path
      end
      send_data data, file_name: "#{params[:report]}.#{params[:format]}"
    else
      redirect_to root_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/interrupts_report/_index_xml.html.erb
<% content_for :sub_title do %>
Исходные данные
<%end%>
<div class='page-content index'>
  <form class="form-horizontal" action="<%= ir_get_result_path %>" method="post" enctype="multipart/form-data" accept-charset="windows-1251">
    <div class="control-group">
      <label class="control-label">Отчет по теоретическим перебоям <span style="color:red; font-size:150%">*</span></label>
      <div class="controls">
        <input type="file" name="tp_report">
      </div>
    </div>
    <div class="control-group">
      <label class="control-label">Отчет по физическим перебоям <span style="color:red; font-size:150%">*</span></label>
      <div class="controls">
        <input type="file" name="fp_report">
      </div>
    </div>
    <div class="control-group">
      <label class="control-label">План поставок <span style="color:red; font-size:150%">*</span></label>
      <div class="controls">
        <input type="file" name="pp_report">
      </div>
    </div>
    <div class="control-group">
      <label class="control-label">Гамма отдела</label>
      <div class="controls">
        <input type="file" name="gl_report">
      </div>
    </div>

    <div class="controls">
      <button type="submit" class="btn btn-primary btn-large">Отправить</button>
    </div>
  <!--/form-->
</div>

app/views/interrupts_report/_index_zip.html.erb
<% content_for :sub_title do %>
Исходные данные
<%end%>
<div class='page-content index'>
  <%= form_tag(ir_get_result_path(data_type: 'zip'),{class: 'form-horizontal', multipart: true, method: :post}) do %>
  <form class="form-horizontal" action="<%= ir_get_result_path %>" method="post" enctype="multipart/form-data" accept-charset="windows-1251">
    <div class="control-group">
      <label class="control-label">Отдел<span style="color:red; font-size:150%">*</span></label>
      <div class="controls">
        <%= select_tag "rayon" , options_for_select([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]) %>
      </div>
    </div>
    <div class="control-group">
      <label class="control-label">ZIP-архив с отчетами<span style="color:red; font-size:150%">*</span></label>
      <div class="controls">
        <input type="file" name="zip_file" accept=".zip">
      </div>
    </div>

    <div class="controls">
      <button type="submit" class="btn btn-primary btn-large">Отправить</button>
    </div>
  <%end%>
  <!--/form-->
</div>

app/views/interrupts_report/index.html.erb
<% content_for :sub_title do %>
Исходные данные
<%end%>
<%= render 'interrupts_report/index_zip' %>

app/views/interrupts_report/report_templs/_details.html.erb
<table border=1 bordercolor="black" style="margin: 10px;">
  <thead>
    <tr>
      <td>
        №
      </td>
      <td>
        LM
      </td> 
      <td>
        Название
      </td>
      <td>
        ТОП / Гамма
      </td>
      <td>
        Запас
      </td>
      <td>
        Виз. MIN
      </td>
      <td>
        Запас ЭКСПО
      </td>
      <td>
        № заказа
      </td>
      <td>
        Дата по договору
      </td>
      <td>
        Первая дата записи
      </td>
    </tr>
  </thead>
  <tbody>
    <% details.each_with_index do |(key,det), c| %>
    <tr>
      <td><%= c+1 %></td>
      <td><%= det.product_code%></td>
      <td><%= det.product_name %></td>
      <td><%= det.top_restocking %> / <%= det.product_info.gamma_group unless det.product_info.nil? %></td>
      <td><%= det.stock_total %></td>
      <td><%= det.product_info.stock_min unless det.product_info.nil? %></td>
      <td><%= det.product_info.reserve_expo unless det.product_info.nil? %></td>
      <td><%= det.order_num  %></td>
      <td><%= det.cmd_date %></td>
      <td><%= (det.pp_records.min{|d1,d2| d1.supply_date<=>d2.supply_date}.supply_date unless det.pp_records.empty?) %></td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/interrupts_report/report_templs/_ovd.html.erb
<div class="result-table">
  <table x:str border=0 cellpadding=0 cellspacing=0 width=950 style='border-collapse:
   collapse;table-layout:fixed;width:712pt; margin:0 auto;'>
   <col width=9 style='width:7pt'>
   <col width=88 style='width:66pt'>
   <col width=81 style='width:61pt'>
   <col width=47 style='width:35pt'>
   <col width=355 style='width:266pt' align="center">
   <col width=114 style='width:85pt' align="center">
   <col width=118 style='width:89pt'  align="center">
   <col width=138 style='width:103pt'>
   <tr class="doc-header">
    <td style='height:22.8pt;width:7pt'></td>
    <td colspan=7 class="text-center" >
      Ежедневный отчет по перебоям в отделе №<%= report.options[:rayon] || "___"%> <%= report.options[:report_date]%>
    </td>
   </tr>
   <tr height=10 style='height:7.8pt'>
    <td ></td>
   </tr>
   <tr class="table-header">
    <td class="first white"></td>
    <td colspan=4 class="bordered">Перебои</td>
    <td class="bordered text-center">ТОП 1 в запасе</td>
    <td class="bordered text-center">Формула</td>
    <td class="bordered text-center" >Количество</td>
   </tr>
   <tr class="table-subheader switcher" data-target="#sw1">
    <td class="first white"></td>
    <td colspan=4 class="bordered">
      Теоретические перебои
    </td>
    <td class="bordered text-center">Итого: кол-во</td>
    <td class="bordered text-center report-code">[1]</td>
    <td class="bordered text-center">
      <%= (details = report.details.select{|key, det| det.report_codes.include? 1}).size %>
    </td>
   </tr>
   <tr class="hide printed-off" id="sw1">
    <td></td>
    <td colspan=7>
      <%= render partial:"interrupts_report/report_templs/details", object: details %>
    </td>
   </tr>
   <tr class="switcher" data-target="#sw2">
    <td class="first white"></td>
    <!--td class=xl32></td-->
    <td colspan=4 class="bordered" style='padding-left:66pt;'>
      Втом числе с <font class="font13">отрицательным запасом</font><font class="font12">:</font>
    </td>
    <td class="bordered text-center">Кол-во</td>
    <td class="bordered text-center report-code">[2]</td>
    <td class="bordered text-center">
      <%= (details=report.details.select{|key, det| det.report_codes.include? 2}).size %>
    </td>
   </tr>
   <tr class="hide printed-off" id="sw2">
    <td></td>
    <td colspan=7>
      <%= render partial:"interrupts_report/report_templs/details", object: details %>
    </td>
   </tr>
   <tr class="yellow-separator">
    <td class="first white"></td>
    <td class="bordered" colspan=7>&nbsp;</td>
   </tr>
   <tr class="table-subheader switcher" data-target="#sw3">
    <td class="first white"></td>
    <td colspan=4 class="bordered">
      Физические перебои
    </td>
    <td class="bordered text-center">Итого: кол-во</td>
    <td class="bordered text-center report-code">[3]=[4]+[5]+[6]</td>
    <td class="bordered text-center">
      <%= (details=report.details.select{|key, det| det.report_codes.include? 3}).size %>
    </td>
   </tr>
   <tr class="hide printed-off" id="sw3">
    <td></td>
    <td colspan=7>
      <%= render partial:"interrupts_report/report_templs/details", object: details %>
    </td>
   </tr>
   <tr class="switcher" data-target="#sw4">
    <td class="first white"></td>
    <td class="bordered"></td>
    <td colspan=3 class="bordered">
      Физические перебои <font class="font13">с запасом</font> больше, чем на одну покупку:</td>
    <td class="bordered text-center">Кол-во</td>
    <td class="bordered text-center report-code">[4]</td>
    <td class="bordered text-center">
      <%= (details=report.details.select{|key, det| det.report_codes.include? 4}).size %>
    </td>
   </tr>
   <tr class="hide printed-off" id="sw4">
    <td></td>
    <td colspan=7>
      <%= render partial:"interrupts_report/report_templs/details", object: details %>
    </td>
   </tr>
   <tr>
    <td class="first white"></td>
    <td class="bordered"></td>
    <td colspan=6 class="bordered">
      Физические перебои <font class="font13">без запаса</font>:
    </td>
   </tr>
   <tr class="switcher" data-target="#sw5">
    <td class="first white"></td>
    <td class="bordered"></td>
    <td colspan=3 class="bordered" style="padding-left:61pt">
      Физические перебои <font class="font13">С заказом</font>
    </td>
    <td class="bordered text-center">Итого: кол-во</td>
    <td class="bordered text-center report-code">[5]=[10]+[11]</td>
    <td class="bordered text-center">
      <%= (details=report.details.select{|key, det| det.report_codes.include? 5}).size %>
    </td>
   </tr>
   <tr class="hide printed-off" id="sw5">
    <td></td>
    <td colspan=7>
      <%= render partial:"interrupts_report/report_templs/details", object: details %>
    </td>
   </tr>
   <tr class="switcher" data-target="#sw6">
    <td class="firs white"></td>
    <td class="bordered"></td>
    <td class=xl43>&nbsp;</td>
    <td class=xl45>&nbsp;</td>
    <td class="bordered">Физические перебои <font class="font13">с заказом</font>
    по причине недопоставки по вине поставщика</td>
    <td class="bordered text-center"40>Кол-во</td>
    <td class="bordered text-center report-code">[10]</td>
    <td class="bordered text-center">
      <%= (details=report.details.select{|key, det| det.report_codes.include? 10}).size %>
    </td>
   </tr>
   <tr class="hide printed-off" id="sw6">
    <td></td>
    <td colspan=7>
      <%= render partial:"interrupts_report/report_templs/details", object: details %>
    </td>
   </tr>
   <tr class="switcher" data-target="#sw7">
    <td class="first white"></td>
    <td class="bordered"></td>
    <td class="bordered"></td>
    <td colspan=2 class="bordered" style="padding-left:35pt;">
      Физические перебои <font class="font13">с заказом</font> ожидаемые в ближайшее время
    </td>
    <td class="bordered text-center">Кол-во</td>
    <td class="bordered text-center report-code">[11]</td>
    <td class="bordered text-center">
      <%= (details=report.details.select{|key, det| det.report_codes.include? 11}).size %>
    </td>
   </tr>
   <tr class="hide printed-off" id="sw7">
    <td></td>
    <td colspan=7>
      <%= render partial:"interrupts_report/report_templs/details", object: details %>
    </td>
   </tr>
   <tr class="switcher" data-target="#sw8">
    <td class="first white"></td>
    <td class="bordered"></td>
    <td class="bordered"></td>
    <td colspan=2 class="bordered">
      Физические перебои <font class="font13">без заказа</font>
    </td>
    <td class="bordered text-center">Итого: кол-во</td>
    <td class="bordered text-center report-code">[6]=[7]+[8]+[9]</td>
    <td class="bordered text-center">
      <%= (details=report.details.select{|key, det| det.report_codes.include? 6}).size %>
    </td>
   </tr>
   <tr class="hide printed-off" id="sw8">
    <td></td>
    <td colspan=7>
      <%= render partial:"interrupts_report/report_templs/details", object: details %>
    </td>
   </tr>
   <tr class="switcher" data-target="#sw9">
    <td class="first white"></td>
    <td class="bordered"></td>
    <td class="bordered"></td>
    <td class="bordered"></td>
    <td class="bordered">Физичесие перебои <font class="font13">без заказа</font>по причине большого франко</td>
    <td class="bordered text-center">Кол-во</td>
    <td class="bordered text-center report-code">[7]</td>
    <td class="bordered text-center">
      <%= (details=report.details.select{|key, det| det.report_codes.include? 7}).size %>
    </td>
   </tr>
   <tr class="hide printed-off" id="sw9">
    <td></td>
    <td colspan=7>
      <%= render partial:"interrupts_report/report_templs/details", object: details %>
    </td>
   </tr>
   <tr class="switcher" data-target="#sw10">
    <td class="first white"></td>
    <td class="bordered"></td>
    <td class="bordered"></td>
    <td class="bordered"></td>
    <td class="bordered">
      Физичесие перебои <font class="font13">без заказа</font> по причине перевода в ТОП 0
    </td>
    <td class="bordered text-center">Кол-во</td>
    <td class="bordered text-center report-code">[8]</td>
    <td class="bordered text-center">
      <%= (details=report.details.select{|key, det| det.report_codes.include? 8}).size %>
    </td>
   </tr>
   <tr class="hide printed-off" id="sw10">
    <td></td>
    <td colspan=7>
      <%= render partial:"interrupts_report/report_templs/details", object: details %>
    </td>
   </tr>
   <tr class="switcher" data-target="#sw11">
    <td class="first white"></td>
    <td class="bordered"></td>
    <td class="bordered"></td>
    <td class="bordered"></td>
    <td class="bordered">Физичесие перебои <font class="font13">без заказа</font> по причине того, что отдел не сделал заказ</td>
    <td class="bordered text-center">Кол-во</td>
    <td class="bordered text-center report-code">[9]</td>
    <td class="bordered text-center">
      <%= (details=report.details.select{|key, det| det.report_codes.include?(9) && det.report_codes.include?(3)}).size %>
    </td>
   </tr>
   <tr class="hide printed-off" id="sw11">
    <td></td>
    <td colspan=7>
      <%= render partial:"interrupts_report/report_templs/details", object: details %>
    </td>
   </tr>
   <tr style="height:5pt">
    <td colspan=8 style='height:5.0pt;'></td>
   </tr>
   <tr>
    <td class="white"></td>
    <td colspan=7 class=" text-center">
      Документ должен быть заполнен каждый будний день и отнесен оператору по вводу данных  до 11 часов утра</td>
   </tr>
  </table>
</div>

app/views/interrupts_report/report_templs/_ovd_div_version.html.erb
<html>
	<head>
		<meta charset="utf-8">
		<style type="text/css">
			.ovd-table{
				display:table;
				width: 949px;
				margin: 0 auto;
			}
			ovd-row{
				display: table-row;
			}
			.ovd-caption{
				display: table-cell;
				height: 40px;
				text-align: center;
				vertical-align: middle;
				font-size: 24px;
				border: 1px solid black;
			}
		</style>
	</head>
<body>
	<div style="width:1024px;height:718px;margin:60px auto 0 auto; background-color:lightblue;">
		<div class="ovd-table">
			<div class="ovd-row">
				<div class="ovd-caption">
					Ежеденвный отчет по перебоям в оделе №
				</div>
			</div>
			<div class="ovd-row">
				<div class="ovd-cell caption">
					Перебои
				</div>
				<div class="ovd-cell clarification">
					ТОП 1 в запасе
				</div>
				<div class="ovd-cell formula">
					Формула
				</div>
				<div class="ovd-cell quantity">
					Количество
				</div>
			</div>
		</div>
	</div>
</body>

app/views/interrupts_report/report_templs/_recom.html.erb
      <div class="ir-recommendations result-table">
		<table><!-- Code [2] -->
			<caption class="doc-header">Необходимо пересчитать товар и, в случае необходимости, провести коррекцию остатаков (<%= (rep2 = report.details.select{|key, val| val.report_codes.include? 2}).size %> позиций)</caption>
			<col width=100></col><!-- LM-код -->
			<col width=270></col><!-- Название -->
			<col width=90></col><!-- Кол-во в БД -->
			<col width=90></col><!-- Кол-во на полке -->
			<col width=90></col><!-- Кол-во на ЭКСПО -->
			<col width=90></col><!-- Кол-во в Stock'e -->
			<col width=180></col><!-- Ответственный -->
			<tr class="table-header bordered">
				<th>LM-код</th>
				<th>Название</th>
				<th>Кол-во в БД</th>
				<th>Кол-во на полке</th>
				<th>Кол-во на ЭКСПО</th>
				<th>Кол-во нa STOCK'e</th>
				<th>Ответственный</th>
			</tr>
           <% rep2.each do |key, det| %>
              <tr class="bordered">
                  <td class="text-center"><%= det.product_code %></td>
                  <td><%= det.product_name %></td>
                  <td class="text-center"><%= det.stock_total %></td>
                  <td class="text-center"></td>
                  <td class="text-center"></td>
                  <td class="text-center"></td>
                  <td></td>
              </tr>
            <%end%>
		</table>
		<table><!-- Code [4] -->
			<caption class="doc-header">Необходимо выставить товар либо провести коррекцию остатаков, в случае расхождения с кол-вом в БД (<%= (rep4 = report.details.select{|key, val| val.report_codes.include? 4}).size %> позиций)</caption>
			<col width=100></col><!-- LM-код -->
			<col width=270></col><!-- Название -->
			<col width=90></col><!-- Кол-во MIN -->
			<col width=90></col><!-- Кол-во в БД -->
			<col width=90></col><!-- Кол-во на полке -->
			<col width=90></col><!-- Кол-во на ЭКСПО -->
			<col width=90></col><!-- Кол-во в Stock'e -->
			<col width=90></col><!-- Кол-во в заказе -->
			<col width=180></col><!-- Ответственный -->
			<tr class="table-header bordered">
				<th>LM-код</th>
				<th>Название</th>
				<th>Кол-во MIN</th>
				<th>Кол-во в БД</th>
				<th>Кол-во на полке</th>
				<th>Кол-во на ЭКСПО</th>
				<th>Кол-во нa STOCK'e</th>
				<th>Кол-во в заказе</th>
				<th>Ответственный</th>
			</tr>
           <% rep4.each do |key, det| %>
              <tr class="bordered">
                  <td class="text-center"><%= det.product_code %></td>
                  <td><%= det.product_name %></td>
                  <td class="text-center"><%= det.product_info.stock_min %></td>
                  <td class="text-center"><%= det.stock_total %></td>
                  <td class="text-center"></td>
                  <td class="text-center"></td>
                  <td class="text-center"></td>
                  <td class="text-center"><%= det.q_ordered %></td>
                  <td></td>
              </tr>
            <%end%>
		</table>
		<table style="display:none"><!-- Code [10] && pp_records.empty? -->
			<caption class="doc-header">Выяснить причину задержки поставки (N позиций)</caption>
			<col width=100></col><!-- LM-код -->
			<col width=270></col><!-- Название -->
			<col width=90></col><!-- Кол-во в заказе -->
			<col width=100></col><!-- Номер заказа -->
			<col width=120></col><!-- Код пост-ка -->
			<col width=270></col><!-- Название пост-ка -->
			<col width=180></col><!-- Ответственный -->
			<tr class="table-header bordered">
				<th>LM-код</th>
				<th>Название</th>
				<th>Кол-во в заказе</th>
				<th>Номер заказа</th>
				<th>Код пост-ка</th>
				<th>Название поставщика</th>
				<th>Ответственный</th>
			</tr>
			<tr class="bordered">
				<td class="text-center">s</td>
				<td>s</td>
				<td class="text-center">s</td>
				<td class="text-center">s</td>
				<td class="text-center">s</td>
				<td >s</td>
				<td class="text-center">s</td>
			</tr>
		</table>
		<table><!-- Code [3]-[1] && top=="1" -->
			<caption class="doc-header">Необходимо выставить ценники (<%= (rep12 = report.details.select{|key, val| val.report_codes.include? 12}).size %> позиций)</caption>
			<col width=100></col><!-- LM-код -->
			<col width=270></col><!-- Название -->
			<col width=90></col><!-- ТОП -->
			<col width=180></col><!-- Ответственный -->
			<tr class="table-header bordered">
				<th>LM-код</th>
				<th>Название</th>
				<th>ТОП</th>
				<th>Ответственный</th>
			</tr>
            <% rep12.each do |key, det| %>
              <tr class="bordered">
                  <td class="text-center"><%= det.product_code %></td>
                  <td><%= det.product_name %></td>
                  <td class="text-center"><%= det.top_restocking %></td>
                  <td class="text-center"></td>
              </tr>
            <%end%>
		</table>
		<table><!-- Code [10] -->
			<caption class="doc-header">Необходимо убрать ценники (<%= (rep8 = report.details.select{|key, val| val.report_codes.include? 8}).size %> позиций)</caption>
			<col width=100></col><!-- LM-код -->
			<col width=270></col><!-- Название -->
			<col width=90></col><!-- ТОП -->
			<col width=180></col><!-- Ответственный -->
			<tr class="table-header bordered">
				<th>LM-код</th>
				<th>Название</th>
				<th>ТОП</th>
				<th>Ответственный</th>
			</tr>
            <% rep8.each do |key, det| %>
              <tr class="bordered">
                  <td class="text-center"><%= det.product_code %></td>
                  <td><%= det.product_name %></td>
                  <td class="text-center"><%= det.top_restocking %></td>
                  <td class="text-center"></td>
              </tr>
            <%end%>
		</table>
		<table><!-- Code [9] -->
			<caption class="doc-header">Необходимо проверить наличие таблички "Извините, товар временно отсутствует" и, в случае необходимости, выставить (<%= (rep_to = report.details.select{|key, val| !val.report_codes.include?(4) && !val.report_codes.include?(8)}).size %> позиций)</caption>
			<col width=100></col><!-- LM-код -->
			<col width=270></col><!-- Название -->
			<col width=140></col><!-- Дата записи в плане поставок -->
			<col width=120></col><!-- Номер заказа -->
			<col width=200></col><!-- Место поставки -->
			<col width=200></col><!-- Статус заказа -->
			<tr class="table-header bordered">
				<th>LM-код</th>
				<th>Название</th>
				<th>Дата записи в плане поставок</th>
				<th>Номер заказа</th>
				<th>Место поставки</th>
				<th>Статус поставки</th>
			</tr>
            <% rep_to.each do |key, det| %>
              <tr class="bordered">
                  <td class="text-center"><%= det.product_code %></td>
                  <td><%= det.product_name %></td>
                  <td class="text-center"><%= (det.pp_records.max{|d1,d2| d1.supply_date<=>d2.supply_date}.supply_date unless det.pp_records.empty?)  || 'Нет записи'%></td>
                  <td class="text-center"><%= det.order_num  %></td>
                  <td class="text-center"><%= det.pp_records.max{|d1,d2| d1.supply_date<=>d2.supply_date}.mesto unless det.pp_records.empty?%></td>
                  <td class="text-center"><%= det.pp_records.max{|d1,d2| d1.supply_date<=>d2.supply_date}.status unless det.pp_records.empty?%></td>
              </tr>
            <%end%>
		</table>
		<table><!-- Code [9] -->
			<caption class="doc-header">Необходимо сделать заказ (<%= (rep9 = report.details.select{|key, val| val.report_codes.include? 9}).size %> позиций)</caption>
			<col width=100></col><!-- LM-код -->
			<col width=270></col><!-- Название -->
			<col width=90></col><!-- Кол-во в БД -->
			<col width=90></col><!-- Кол-во MIN -->
			<col width=120></col><!-- Код пост-ка -->
			<col width=270></col><!-- Название пост-ка -->
			<col width=180></col><!-- Ответственный -->
			<tr class="table-header bordered">
				<th>LM-код</th>
				<th>Название</th>
				<th>Кол-во в БД</th>
				<th>Кол-во MIN</th>
				<th>Код пост-ка</th>
				<th>Название поставщика</th>
				<th>Ответственный</th>
			</tr>
            <% rep9.each do |key, det| %>
              <tr class="bordered">
                  <td class="text-center"><%= det.product_code %></td>
                  <td><%= det.product_name %></td>
                  <td class="text-center"><%= det.stock_total %></td>
                  <td class="text-center"><%= det.product_info.stock_min %></td>
                  <td class="text-center"><%= det.suppl_code %></td>
                  <td class="text-center"><%= det.suppl_name %></td>
                  <td class="text-center"></td>
              </tr>
            <%end%>
		</table>
      </div>

app/views/interrupts_report/result.html.erb
<%= link_to "Назад", ir_index_path, class:"btn btn-info btn-large pull-left printed-off", style: "margin-left: 1ex" %>
<% content_for :sub_title do %>
  Результат обработки
<%end%>
<div class='page-content result' >
         <ul class="nav nav-tabs printed-off" id="myTab">
           <li class="active"><a href="#recom"  data-toggle="tab">Рекомендации для отдела</a></li>
           <li><a href="#ovd" data-toggle="tab">Форма для отдела ввода данных</a></li>
         </ul>

         <div class="tab-content">
           <div class="tab-pane active printed" id="recom">
            <div class="btn-group printed-off pull-right" style="margin:10px">
              <%= link_to "Версия для печати", ir_print_path(report:"recom",format:"xls"), :class => "btn" %>
            </div>
             <%=render( partial: 'interrupts_report/report_templs/recom', locals:{report: report}) if report.is_a? LmInterruptsReport %>
           </div>
           <div class="tab-pane printed" id="ovd">
            <div class="btn-group printed-off pull-right" style="margin:10px">
              <%= link_to "Версия для печати", ir_print_path(report:"ovd",format:"xls"), :class => "btn" %>
            </div>
             <%=render( partial: 'interrupts_report/report_templs/ovd', locals:{report: report}) if report.is_a? LmInterruptsReport %>
           </div>
         </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ma001</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>